sudo: false
language: python
cache: pip
install:
  - pip install tox
script:
  - tox
after_success:
  - |
    if [[ "${TOXENV%-codecov}" != "$TOXENV" ]]; then
      pip install codecov
      flags="${TOXENV//-/ }"
      flags="${flags//./}"
      codecov --name $TOXENV --flags $flags
    fi
jobs:
  include:
    - stage: test
      python: '2.7.13'
      env: TOXENV=docs
    - python: '2.7.13'
      env: TOXENV=py27-dj111-drf37-codecov
    - python: '3.4'
      env: TOXENV=py34-dj111-drf37-codecov
    - python: '3.5'
      env: TOXENV=py35-dj111-drf37-codecov
    - python: '3.6'
      env: TOXENV=py36-dj111-drf37-codecov
    - python: '2.7.13'
      env: TOXENV=py27-dj111-drf38-codecov
    - python: '3.4'
      env: TOXENV=py34-dj111-drf38-codecov
    - python: '3.5'
      env: TOXENV=py35-dj111-drf38-codecov
    - python: '3.6'
      env: TOXENV=py36-dj111-drf38-codecov
    - stage: deploy
      python: '2.7.13'
      env: TOXENV=py27-dj111-drf37
      deploy:
        provider: pypi
        user: styria
        password:
          secure: vgeBovjCjamXAZjIa9IObvJn0qkMSRqO+iW7SIUn8aQJCUoAkKohdCFuCPgvsX0txzGOn2WQrTOvHf34oLcb9psAclh3JmqXqr9JmP9yjG9+vuf2uA4S9mGM+Sf4bQQ7NEEWqy0i7T9YAJbT09ncPR4VzEzOD73uxSXW7Y02sN0dO47r1kog7Mmc+fJIl0bs09z6JR0mhhIJV14JhAdIBO0ZlqlK/G3+OOK7WtaQSI6JAqz49DGq7MxqUvlYElgfWt0j3I2W7I7c5WQtka9ASsvWQVA7E/Af6HhLbhnrRImvVYNhzZQ2TApIVdmY5+MdEP6RGudn7jjgvD8fVldfazXxtzvO2TIuXvO8QAPGjOwXOd9mKimlGGeiWB1TZBi6rUMi0O6IaJ3Mf8jnnkV06IxIc0B9CnUHvqBCExBWH1zVqD0AkyoX+uDg7pSEjP/Tp7iuwabheSOldrVNCsmfTQ/Uifd5p/X56UU7KGyJknNhjyGqBQzah80dfXISAIYtWetgGgvU3thg8qFHGGWzZqukEzkbOzzGYqBshomP4JsFt2wOeOpgSC9hqydOXKRBba5RLZcDxCFrx/ZjJp78gmp70OW9cXBpeJI/kQTb078d/2RZUTnM0G6kMXKEQCkrk/bCI4BqUC8vWPzuMDYnXMh87VUFRUZ+v9kg2eSJIpk=
        skip_cleanup: true
        skip_existing: true
        distributions: "sdist bdist_wheel"
        on:
          tags: true
          branch: master
stages:
  - test
  - name: deploy
    if: tag IS present
